services:
  amazon-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: amazon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Avoid conflict with worldSim's default 5432
  amazon-web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:abc123@amazon-db:5432/amazon
      UPS_ENDPOINT: http://ups:9000  # Negotiated with IG
      WORLD_HOST: worldsim           # Provided by their compose or local change to localhost
      WORLD_PORT_A: 23456
    depends_on:
      - amazon-db
    ports:
      - "8080:8080"
volumes:
  dbdata:
