services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: amazon
      POSTGRES_PASSWORD: amazon
      POSTGRES_DB: amazon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  amazon-web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://amazon:amazon@db:5432/amazon
      UPS_ENDPOINT: http://ups:9000  # Negotiated with IG
      WORLD_HOST: worldsim           # Provided by their compose or local change to localhost
      WORLD_PORT_A: 23456
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  pgdata:
