services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: amazon
    restart: always
    volumes:
      - data-volume:/var/lib/postgresql/data

  web-init:
    build: ./web-app
    command: bash -c "./wait-for-it.sh db:5432 --strict -- ./initserver.sh"
    volumes:
      - ./web-app:/code
    depends_on:
      - db

  web:
    build: ./web-app
    user: nobody
    command: /code/runserver.sh
    volumes:
      - ./web-app:/code
    expose:
      - "8000"
    depends_on:
      - web-init

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    environment:
      - SERVER_NAME=${HOSTNAME:-localhost}
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.d/40-template-subst.sh
    depends_on:
      - web

  daemon:
    build: ./daemon
    command: bash -c "./gradlew run"
    environment:
      - WORLD_HOST=backup-vm.colab.duke.edu
      - WORLD_PORT=23456
      - UPS_HOST=host.docker.internal
      - UPS_PORT=34567
    ports:
      - "8888:8888"
    depends_on:
      - web

volumes:
  data-volume:
