# Generated by Django 3.1.8 on 2025-04-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
